# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171205_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-specified', 'Not spacified'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
