# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171216_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not spacified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
