# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171220_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not spacified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
